[pytest]
markers =
    cart: mark a test as part of cart tests
    checkout: mark a test as part of checkout tests
    login: mark a test as part of login tests
    negative: mark a test as negative scenario